feature(next-migration): hospitale starter
bcms/starters pull request #10
Opened 2023-09-05 08:24 UTC by siradji

2023-09-05 09:01 UTC, siradji commented
@Momciloo , @Bbanez, @boris-becomes. Please have a look and let me know you thoughts. Thanks in advance

2023-09-06 08:16 UTC, Bbanez requested changes

2023-09-06 08:16 UTC, Bbanez commented on next/hospitale/components/Btn.tsx
> +import ArrowIcon from '@/../../blog/assets/icons/arrow.svg';
File imports should be scoped to Hospitale directory.

2023-09-06 09:19 UTC, Bbanez approved these changes

2023-09-06 09:19 UTC, merged